# Example for: model.assess_normalized_dope()

from modeller import *
from modeller.scripts import complete_pdb

env = environ()
env.libs.topology.read(file='$(LIB)/top_heav.lib')
env.libs.parameters.read(file='$(LIB)/par.lib')

# Read a model previously generated by Modeller's automodel class
mdl = complete_pdb(env, 'sequenceA.B99990003.pdb')

thing = mdl.get_normalized_dope_profile()
indexthing = [1, 26, 28, 43, 64, 103, 104, 105, 106, 126, 127, 128, 129, 148, 151, 176, 238, 239, 240, 243, 263, 264, 265, 268, 270, 343, 344, 345]
print("\n", "Local dope score thing for model based on template 1EWK:")
for i in indexthing:
    print(i + 1, thing[i])
